# SPDX-FileCopyrightText: 2026 Kartoza <info@kartoza.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate the monthly report archive page for the MkDocs site.

Scans a directory of ``qgis-news-YYYY-MM.pdf`` files and writes a
``docs/reports/index.md`` that features the newest report and lists the rest
as a per-year grid. Run by the docs workflow after the reports published on
the ``gh-pages`` branch have been restored into ``docs/reports/``.

Usage:
    python scripts/generate_reports_index.py [--reports-dir DIR] [--output FILE]
"""

from __future__ import annotations

import argparse
import re
from datetime import date
from pathlib import Path

REPORT_RE = re.compile(r"^qgis-news-(\d{4})-(\d{2})\.pdf$")

MONTH_NAMES = (
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
)

HEADER = """<!-- SPDX-FileCopyrightText: 2026 Kartoza <info@kartoza.com> -->
<!-- SPDX-License-Identifier: GPL-3.0-or-later -->
<!-- Generated by scripts/generate_reports_index.py - do not edit by hand. -->

# Monthly Reports

Every month the gatherer runs on the last Thursday and publishes the report
here. Each PDF is the full slide deck: releases, merged pull requests,
community activity, analytics charts and the YouTube round-up for that month.
"""

EMPTY_BODY = """
<div class="kz-empty-note" markdown>

No reports have been published yet. The first one appears after the
[monthly automation](../admin-guide/automation.md) runs on the last Thursday
of the month, or as soon as someone triggers it by hand.

</div>
"""

FOOTER = """
<div class="kz-footer-credits" markdown>
Made with 💗 by [Kartoza](https://kartoza.com) &middot;
[Sponsor on GitHub](https://github.com/sponsors/kartoza) &middot;
[Repository](https://github.com/timlinux/qgis-news-gatherer)
</div>
"""


class Report:
    """One published monthly report PDF."""

    def __init__(self, path: Path, year: int, month: int) -> None:
        self.path = path
        self.year = year
        self.month = month

    @property
    def month_name(self) -> str:
        """Full month name, e.g. "August"."""
        return MONTH_NAMES[self.month - 1]

    @property
    def title(self) -> str:
        """Human readable month and year."""
        return f"{self.month_name} {self.year}"

    @property
    def size_mb(self) -> float:
        """File size in megabytes."""
        return self.path.stat().st_size / 1_000_000

    @property
    def sort_key(self) -> tuple[int, int]:
        """Chronological sort key."""
        return (self.year, self.month)


def find_reports(reports_dir: Path) -> list[Report]:
    """Return every report PDF in ``reports_dir``, newest first."""
    reports = []
    for path in reports_dir.glob("qgis-news-*.pdf"):
        match = REPORT_RE.match(path.name)
        if not match:
            continue
        year, month = int(match.group(1)), int(match.group(2))
        if not 1 <= month <= 12:
            continue
        reports.append(Report(path, year, month))
    return sorted(reports, key=lambda r: r.sort_key, reverse=True)


def render_latest(report: Report) -> str:
    """Render the featured card for the most recent report."""
    return f"""
<div class="kz-report-latest" markdown>
<div class="kz-report-latest__body" markdown>
<span class="kz-report-latest__label">Latest report</span>
### {report.title}
<span class="kz-report-latest__meta">PDF &middot; {report.size_mb:.1f} MB</span>
</div>
<div class="kz-cta" markdown>
[:material-download: Download PDF]({report.path.name}){{ .kz-cta__primary }}
</div>
</div>
"""


def render_year(year: int, reports: list[Report]) -> str:
    """Render one year's grid of report cards."""
    lines = [f'\n## <span class="kz-year-heading">{year}</span>\n']
    lines.append('<div class="grid cards kz-report-grid" markdown>\n')
    for report in reports:
        lines.append(
            f"-   <span class=\"kz-report-card__month\">{report.month_name}</span>\n"
            f"    <span class=\"kz-report-card__meta\">PDF &middot; "
            f"{report.size_mb:.1f} MB</span>\n\n"
            f"    [:octicons-download-24: Download]({report.path.name})\n"
        )
    lines.append("\n</div>\n")
    return "\n".join(lines)


def render(reports: list[Report]) -> str:
    """Render the whole archive page."""
    if not reports:
        return HEADER + EMPTY_BODY + FOOTER

    body = [HEADER, render_latest(reports[0])]

    years: dict[int, list[Report]] = {}
    for report in reports:
        years.setdefault(report.year, []).append(report)

    for year in sorted(years, reverse=True):
        body.append(render_year(year, years[year]))

    count = len(reports)
    noun = "report" if count == 1 else "reports"
    body.append(
        f"\n!!! info \"Archive\"\n\n"
        f"    {count} {noun} published, most recent first. "
        f"Generated {date.today().isoformat()}.\n"
    )
    body.append(FOOTER)
    return "".join(body)


def main() -> int:
    """Entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--reports-dir",
        type=Path,
        default=Path("docs/reports"),
        help="Directory holding the published report PDFs",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/reports/index.md"),
        help="Markdown file to write",
    )
    args = parser.parse_args()

    args.reports_dir.mkdir(parents=True, exist_ok=True)
    reports = find_reports(args.reports_dir)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(reports))

    print(f"Wrote {args.output} with {len(reports)} report(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
